version: '2'

services:
  nginx:
    container_name: apiScrum_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/:/var/log/nginx/
    links:
      - php
    networks:
      - code-network
    restart: always

  php:
    container_name: apiScrum_php
    build: docker/php
    volumes:
      - ./server/:/var/www/laravel
    links:
      - mariadb
    networks:
      - code-network
    entrypoint:
      - php-fpm
    restart: always

  mariadb:
    container_name: apiScrum_mariadb
    image: mariadb:latest
    ports:
      - "3307:3306"
    networks:
      - code-network
    environment:
      MYSQL_DATABASE: apiscrum
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/database:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: apiScrum_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - mariadb
    environment:
      PMA_HOST: apiScrum_mysql
      PMA_PORT: "3306"
    networks:
      - code-network
    restart: always

  #nodejs:
  #  container_name: nodejs
  #  build: docker/nodejs
  #  command: ng serve
  #  volumes:
  #    - ./client/:/usr/src/app
  #  ports:
  #    - "4200:4200"
  #    - "49153:49153"
  #  networks:
  #    - code-network
  #  restart: always

networks:
  code-network:
     driver: bridge
